# This file is auto-generated. DO NOT MODIFY!

SAFE_C_FILES :=    \
    build/src/boot/z_std_dma.o    \
    build/src/code/audioMgr.o    \
    build/src/code/audio_data.o    \
    build/src/code/audio_effects.o    \
    build/src/code/audio_heap.o    \
    build/src/code/audio_init_params.o    \
    build/src/code/audio_load.o    \
    build/src/code/audio_playback.o    \
    build/src/code/audio_seqplayer.o    \
    build/src/code/audio_sound_params.o    \
    build/src/code/audio_synthesis.o    \
    build/src/code/code_800430A0.o    \
    build/src/code/code_80043480.o    \
    build/src/code/code_80069420.o    \
    build/src/code/code_8006C3A0.o    \
    build/src/code/code_8006C510.o    \
    build/src/code/code_80097A00.o    \
    build/src/code/code_800A9F30.o    \
    build/src/code/code_800ACE70.o    \
    build/src/code/code_800AD920.o    \
    build/src/code/code_800BB0A0.o    \
    build/src/code/code_800C3C20.o    \
    build/src/code/code_800D2E30.o    \
    build/src/code/code_800D31A0.o    \
    build/src/code/code_800E4FE0.o    \
    build/src/code/code_800E6840.o    \
    build/src/code/code_800EC960.o    \
    build/src/code/code_800F7260.o    \
    build/src/code/code_800F9280.o    \
    build/src/code/code_800FC620.o    \
    build/src/code/code_800FCE80.o    \
    build/src/code/code_800FD970.o    \
    build/src/code/code_80106860.o    \
    build/src/code/code_801068B0.o    \
    build/src/code/db_camera.o    \
    build/src/code/debug_malloc.o    \
    build/src/code/fault.o    \
    build/src/code/fault_drawer.o    \
    build/src/code/flg_set.o    \
    build/src/code/fmodf.o    \
    build/src/code/game.o    \
    build/src/code/gamealloc.o    \
    build/src/code/gfxprint.o    \
    build/src/code/graph.o    \
    build/src/code/irqmgr.o    \
    build/src/code/jpegdecoder.o    \
    build/src/code/jpegutils.o    \
    build/src/code/listalloc.o    \
    build/src/code/loadfragment2.o    \
    build/src/code/logseverity.o    \
    build/src/code/main.o    \
    build/src/code/mempak.o    \
    build/src/code/mtxuty-cvt.o    \
    build/src/code/padmgr.o    \
    build/src/code/padsetup.o    \
    build/src/code/padutils.o    \
    build/src/code/PreRender.o    \
    build/src/code/printutils.o    \
    build/src/code/rcp_utils.o    \
    build/src/code/relocation.o    \
    build/src/code/sched.o    \
    build/src/code/shrink_window.o    \
    build/src/code/sleep.o    \
    build/src/code/speed_meter.o    \
    build/src/code/system_malloc.o    \
    build/src/code/sys_cfb.o    \
    build/src/code/sys_math.o    \
    build/src/code/sys_math3d.o    \
    build/src/code/sys_math_atan.o    \
    build/src/code/sys_matrix.o    \
    build/src/code/sys_ucode.o    \
    build/src/code/title_setup.o    \
    build/src/code/TwoHeadArena.o    \
    build/src/code/ucode_disas.o    \
    build/src/code/z_actor.o    \
    build/src/code/z_actor_dlftbls.o    \
    build/src/code/z_bgcheck.o    \
    build/src/code/z_camera.o    \
    build/src/code/z_camera_data.o    \
    build/src/code/z_cheap_proc.o    \
    build/src/code/z_collision_btltbls.o    \
    build/src/code/z_collision_check.o    \
    build/src/code/z_common_data.o    \
    build/src/code/z_construct.o    \
    build/src/code/z_debug.o    \
    build/src/code/z_debug_display.o    \
    build/src/code/z_demo.o    \
    build/src/code/z_DLF.o    \
    build/src/code/z_draw.o    \
    build/src/code/z_effect.o    \
    build/src/code/z_effect_soft_sprite.o    \
    build/src/code/z_effect_soft_sprite_dlftbls.o    \
    build/src/code/z_effect_soft_sprite_old_init.o    \
    build/src/code/z_eff_blure.o    \
    build/src/code/z_eff_shield_particle.o    \
    build/src/code/z_eff_spark.o    \
    build/src/code/z_eff_ss_dead.o    \
    build/src/code/z_elf_message.o    \
    build/src/code/z_en_a_keep.o    \
    build/src/code/z_en_item00.o    \
    build/src/code/z_face_reaction.o    \
    build/src/code/z_fbdemo.o    \
    build/src/code/z_fbdemo_circle.o    \
    build/src/code/z_fbdemo_fade.o    \
    build/src/code/z_fbdemo_triforce.o    \
    build/src/code/z_fbdemo_wipe1.o    \
    build/src/code/z_fcurve_data_skelanime.o    \
    build/src/code/z_frame_advance.o    \
    build/src/code/z_game_dlftbls.o    \
    build/src/code/z_game_over.o    \
    build/src/code/z_horse.o    \
    build/src/code/z_jpeg.o    \
    build/src/code/z_kaleido_manager.o    \
    build/src/code/z_kaleido_scope_call.o    \
    build/src/code/z_kaleido_setup.o    \
    build/src/code/z_kanfont.o    \
    build/src/code/z_kankyo.o    \
    build/src/code/z_lib.o    \
    build/src/code/z_lifemeter.o    \
    build/src/code/z_lights.o    \
    build/src/code/z_malloc.o    \
    build/src/code/z_map_data.o    \
    build/src/code/z_map_exp.o    \
    build/src/code/z_map_mark.o    \
    build/src/code/z_message_PAL.o    \
    build/src/code/z_moji.o    \
    build/src/code/z_msgevent.o    \
    build/src/code/z_olib.o    \
    build/src/code/z_onepointdemo.o    \
    build/src/code/z_onepointdemo_data.o    \
    build/src/code/z_parameter.o    \
    build/src/code/z_path.o    \
    build/src/code/z_play.o    \
    build/src/code/z_player_call.o    \
    build/src/code/z_player_lib.o    \
    build/src/code/z_prenmi.o    \
    build/src/code/z_prenmi_buff.o    \
    build/src/code/z_quake.o    \
    build/src/code/z_rcp.o    \
    build/src/code/z_room.o    \
    build/src/code/z_sample.o    \
    build/src/code/z_scene.o    \
    build/src/code/z_scene_table.o    \
    build/src/code/z_skelanime.o    \
    build/src/code/z_skin.o    \
    build/src/code/z_skin_awb.o    \
    build/src/code/z_skin_matrix.o    \
    build/src/code/z_sound_source.o    \
    build/src/code/z_sram.o    \
    build/src/code/z_ss_sram.o    \
    build/src/code/z_view.o    \
    build/src/code/z_vimode.o    \
    build/src/code/z_vismono.o    \
    build/src/code/z_vr_box.o    \
    build/src/code/z_vr_box_draw.o    \
    build/src/code/__osMalloc.o    \
    build/src/dmadata/dmadata.o    \
    build/src/elf_message/elf_message_field.o    \
    build/src/elf_message/elf_message_ydan.o    \
    build/src/libultra/gu/cosf.o    \
    build/src/libultra/gu/coss.o    \
    build/src/libultra/gu/lookat.o    \
    build/src/libultra/gu/lookathil.o    \
    build/src/libultra/gu/ortho.o    \
    build/src/libultra/gu/perspective.o    \
    build/src/libultra/gu/position.o    \
    build/src/libultra/gu/rotate.o    \
    build/src/libultra/gu/sinf.o    \
    build/src/libultra/gu/sins.o    \
    build/src/libultra/gu/sintable.o    \
    build/src/libultra/gu/sqrtf.o    \
    build/src/libultra/gu/us2dex.o    \
    build/src/libultra/io/aigetlen.o    \
    build/src/libultra/io/aisetfreq.o    \
    build/src/libultra/io/aisetnextbuf.o    \
    build/src/libultra/io/cartrominit.o    \
    build/src/libultra/io/contpfs.o    \
    build/src/libultra/io/contquery.o    \
    build/src/libultra/io/contramread.o    \
    build/src/libultra/io/contramwrite.o    \
    build/src/libultra/io/contreaddata.o    \
    build/src/libultra/io/controller.o    \
    build/src/libultra/io/contsetch.o    \
    build/src/libultra/io/crc.o    \
    build/src/libultra/io/devmgr.o    \
    build/src/libultra/io/dpgetstat.o    \
    build/src/libultra/io/dpsetstat.o    \
    build/src/libultra/io/driverominit.o    \
    build/src/libultra/io/epidma.o    \
    build/src/libultra/io/epirawdma.o    \
    build/src/libultra/io/epirawread.o    \
    build/src/libultra/io/epirawwrite.o    \
    build/src/libultra/io/epiread.o    \
    build/src/libultra/io/epiwrite.o    \
    build/src/libultra/io/motor.o    \
    build/src/libultra/io/pfsallocatefile.o    \
    build/src/libultra/io/pfschecker.o    \
    build/src/libultra/io/pfsdeletefile.o    \
    build/src/libultra/io/pfsfilestate.o    \
    build/src/libultra/io/pfsfindfile.o    \
    build/src/libultra/io/pfsfreeblocks.o    \
    build/src/libultra/io/pfsgetstatus.o    \
    build/src/libultra/io/pfsinitpak.o    \
    build/src/libultra/io/pfsisplug.o    \
    build/src/libultra/io/pfsreadwritefile.o    \
    build/src/libultra/io/pfsselectbank.o    \
    build/src/libultra/io/piacs.o    \
    build/src/libultra/io/pigetcmdq.o    \
    build/src/libultra/io/pimgr.o    \
    build/src/libultra/io/pirawdma.o    \
    build/src/libultra/io/si.o    \
    build/src/libultra/io/siacs.o    \
    build/src/libultra/io/sirawdma.o    \
    build/src/libultra/io/sirawread.o    \
    build/src/libultra/io/sirawwrite.o    \
    build/src/libultra/io/sp.o    \
    build/src/libultra/io/spgetstat.o    \
    build/src/libultra/io/sprawdma.o    \
    build/src/libultra/io/spsetpc.o    \
    build/src/libultra/io/spsetstat.o    \
    build/src/libultra/io/sptask.o    \
    build/src/libultra/io/sptaskyield.o    \
    build/src/libultra/io/sptaskyielded.o    \
    build/src/libultra/io/vi.o    \
    build/src/libultra/io/viblack.o    \
    build/src/libultra/io/viextend.o    \
    build/src/libultra/io/vigetcurrcontext.o    \
    build/src/libultra/io/vigetcurrframebuf.o    \
    build/src/libultra/io/vigetnextframebuf.o    \
    build/src/libultra/io/vimgr.o    \
    build/src/libultra/io/vimodefpallan1.o    \
    build/src/libultra/io/vimodempallan1.o    \
    build/src/libultra/io/vimodentsclan1.o    \
    build/src/libultra/io/vimodepallan1.o    \
    build/src/libultra/io/visetevent.o    \
    build/src/libultra/io/visetmode.o    \
    build/src/libultra/io/visetspecial.o    \
    build/src/libultra/io/visetxscale.o    \
    build/src/libultra/io/visetyscale.o    \
    build/src/libultra/io/viswapbuf.o    \
    build/src/libultra/io/viswapcontext.o    \
    build/src/libultra/libc/absf.o    \
    build/src/libultra/libc/ldiv.o    \
    build/src/libultra/libc/sqrt.o    \
    build/src/libultra/libc/string.o    \
    build/src/libultra/os/afterprenmi.o    \
    build/src/libultra/os/createmesgqueue.o    \
    build/src/libultra/os/createthread.o    \
    build/src/libultra/os/dequeuethread.o    \
    build/src/libultra/os/destroythread.o    \
    build/src/libultra/os/getactivequeue.o    \
    build/src/libultra/os/getcurrfaultedthread.o    \
    build/src/libultra/os/gethwintrroutine.o    \
    build/src/libultra/os/getmemsize.o    \
    build/src/libultra/os/getthreadid.o    \
    build/src/libultra/os/getthreadpri.o    \
    build/src/libultra/os/gettime.o    \
    build/src/libultra/os/initialize.o    \
    build/src/libultra/os/jammesg.o    \
    build/src/libultra/os/recvmesg.o    \
    build/src/libultra/os/resetglobalintmask.o    \
    build/src/libultra/os/sendmesg.o    \
    build/src/libultra/os/seteventmesg.o    \
    build/src/libultra/os/setglobalintmask.o    \
    build/src/libultra/os/sethwintrroutine.o    \
    build/src/libultra/os/setthreadpri.o    \
    build/src/libultra/os/settimer.o    \
    build/src/libultra/os/startthread.o    \
    build/src/libultra/os/stopthread.o    \
    build/src/libultra/os/stoptimer.o    \
    build/src/libultra/os/timerintr.o    \
    build/src/libultra/os/virtualtophysical.o    \
    build/src/libultra/os/yieldthread.o    \
    build/src/libultra/rmon/sprintf.o    \
    build/src/libultra/rmon/xldtob.o    \
    build/src/libultra/rmon/xlitob.o    \
    build/src/libultra/rmon/xprintf.o    \
